### ISSUE TITLE
Plot graph's backbone as straight line

### ISSUE THREAD

**Issue by starskyzheng** [TF-Chan-Lab/panGraphViewer#2]
When there were lots of node, they will coiled together like a ball of thread.
Can you add an option before plot, which will plot graph's backbone as straight line and other nodes treated as bubble?

**Comment by yuxuanyuan** [comment]
Hi @q623928815, 

We are working on the code and the new major updated version will be relased in the next few days.

**Comment by starskyzheng** [comment]
Thanks for your reply.
i thought the node in reverse should not be separated, so i just create a pull request to show all relative nodes and paths.
I also add `path-title` in line 741 to show the status of reverse or forward in browser. but since i know nothing about js, can you help me to do that?

**Comment by yuxuanyuan** [comment]
Thanks @StarSkyZheng. We also noticed some problems in v1.0

We are revising the code and rewriting some to make the tool more robust. As i mentioned, we are working on a major update of the tool, we cannot accept your pull request at the moment until our new update is released. 

By the way, we appreciate your interest of this tool and kind support.

**Comment by starskyzheng** [comment]
Sure, can't wait to see that new version!
