### ISSUE TITLE
conda install directions fail for panGraphViewerWeb

### ISSUE THREAD

**Issue by nathanweeks** [TF-Chan-Lab/panGraphViewer#4]
The conda-based [installation instructions for panGraphViewerWeb](https://github.com/TF-Chan-Lab/panGraphViewer/wiki/Installation#web-browser-based-version) listed the wiki fail with the following error:

```
No match found for: fontawesome-free. Search: *fontawesome-free*
The following packages are not available from current channels:

  - fontawesome-free
```

A search for `fontawesome-free` at https://anaconda.org/ reveals no packages.

**Comment by rickyma1** [comment]
Sorry for overlooking your post. Thanks for informing the problem. "fontawesome-free" needs to be installed through pip instead. The installation instructions for panGraphViewerWeb has been updated accordingly. Thanks.

**Comment by nathanweeks** [comment]
Thanks @rickyma1 . The update may not have been pushed to this repository? (last commit 7 months ago...)

**Comment by rickyma1** [comment]
Hi @nathanweeks . I was referring to the Wiki page at https://github.com/TF-Chan-Lab/panGraphViewer/wiki/Installation

For "Web browser-based version", step 1 is updated as below:
    ```
    conda config --add channels conda-forge
    ```
    ```
    conda config --add channels bioconda
    ```
    ```
    conda install pip django==3.1.3 django-bootstrap4 requests django-environ djangorestframework configparser natsort networkx bokeh==2.2.3 dna_features_viewer pandas whitenoise jinja2==3.0
    ```
    ```
    pip install fontawesome-free==5.15
    ```

**Comment by nathanweeks** [comment]
@rickyma1 Thanks for the clarification! I somehow failed to review the original issue in its entirety before responding :-)
